name: Warm Up

on:
  workflow_dispatch:
  
  schedule:
    - cron:  "30 * * * *"

concurrency: 
  group: warming${{github.ref}}
  cancel-in-progress: true

jobs:
  generate:
    name: Warm Up
    runs-on: ubuntu-latest

    steps:
      - name: Check out Respository
        uses: actions/checkout@v3
        with:
          ref: main
      
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
          cache: "pip"
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Warm Up
        run: python cache_warmer.py
